title: EBS
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for EBS volumes monitored with the AWS integration
icon:
    name: ebs
    background: orange
    foreground: white
